service: checktickets

frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1

#  stage: dev

functions:
  checkTickets:
    handler: handler.checkTickets
    events:
      - httpApi:
          path: /checkTickets
          method: get
